[ARC-2042] create movie app ui
Gio481/MovieApp pull request #1
Opened 2022-03-15 15:18 UTC by Gio481

https://spaceneobank.atlassian.net/browse/ARC-2042

2022-03-15 15:26 UTC, GiorgiMamagulashvili1 requested changes

2022-03-15 15:26 UTC, GiorgiMamagulashvil1 commented on app/src/main/java/com/example/movieapp/presentation/ui/movie_details/MovieDetailsFragment.kt
> +    override val viewModel: MovieDetailsViewModel by activityViewModels()
activityViewModels() რატო გჭირდება აქ? viewModels() აჯობებს მგონი

2022-03-15 15:26 UTC, GiorgiMamagulashvili1 commented on app/src/main/java/com/example/movieapp/presentation/ui/movies_collection/MoviesCollectionFragment.kt
> +    override val viewModel: MoviesCollectionViewModel by activityViewModels()
activityViewModels() რატო გჭირდება აქ? viewModels() აჯობებს მგონი

2022-03-15 15:26 UTC, GiorgiMamagulashvili1 commented on app/src/main/res/layout/fragment_movie_details.xml
> +        android:layout_height="@dimen/view_dynamic_size"
დიმენშენბს ჯობია სახელში ჩანდეს რამდენი dp ან sp ია

2022-03-15 15:26 UTC, GiorgiMamagulashvili1 commented on app/src/main/res/drawable/view_round_background.xml
> +            <corners android:radius="50dp"/>
დიმენშენებით დაუწერე ზომები დრევებლებსაც

2022-03-15 15:26 UTC, GiorgiMamagulashvili1 commented on app/src/main/res/layout/fragment_movie_details.xml
> +        android:layout_margin="@dimen/rating_text_view_margin"
აქაც ჯობია რომ ზოგადი სახელები ჰქონდეთ დიმენშენებს

2022-03-15 15:26 UTC, GiorgiMamagulashvili1 commented on app/src/main/res/values/dimens.xml
> +    <dimen name="splash_logo_sizes">200dp</dimen>
სახელები დაურეფაქტორე

2022-03-15 15:31 UTC, Gio481 commented on app/src/main/java/com/example/movieapp/presentation/ui/movie_details/MovieDetailsFragment.kt
> +    override val viewModel: MovieDetailsViewModel by activityViewModels()
viewModels() ზე იქრაშება აპლიკაცია და მაგიტო მიწერია activity - ით

2022-03-15 18:09 UTC, GiorgiMamagulashvil1 approved these changes

2022-03-16 08:51 UTC, shioandghuladze approved these changes

2022-03-16 10:38 UTC, AleksandreGalogreBaramidze approved these changes

2022-03-16 10:50 UTC, Gio481 commented on app/src/main/java/com/example/movieapp/presentation/ui/movie_details/MovieDetailsFragment.kt
> +    override val viewModel: MovieDetailsViewModel by activityViewModels()
done

2022-03-16 10:50 UTC, Gio481 commented on app/src/main/java/com/example/movieapp/presentation/ui/movies_collection/MoviesCollectionFragment.kt
> +    override val viewModel: MoviesCollectionViewModel by activityViewModels()
done

2022-03-16 10:50 UTC, Gio481 commented on app/src/main/res/layout/fragment_movie_details.xml
> +        android:layout_height="@dimen/view_dynamic_size"
done

2022-03-16 10:50 UTC, Gio481 commented on app/src/main/res/drawable/view_round_background.xml
> +            <corners android:radius="50dp"/>
done

2022-03-16 10:50 UTC, Gio481 commented on app/src/main/res/layout/fragment_movie_details.xml
> +        android:layout_margin="@dimen/rating_text_view_margin"
done

2022-03-16 10:50 UTC, Gio481 commented on app/src/main/res/values/dimens.xml
> +    <dimen name="splash_logo_sizes">200dp</dimen>
done

2022-03-16 10:52 UTC, gioqemoklidze approved these changes

2022-03-16 10:52 UTC, merged