[ARC-2046] implement room database
Gio481/MovieApp pull request #3
Opened 2022-03-17 10:41 UTC by Gio481

https://spaceneobank.atlassian.net/browse/ARC-2046

2022-03-17 10:49 UTC, shioandghuladze requested changes

2022-03-17 10:49 UTC, shioandghuladze commented on app/src/main/java/com/example/movieapp/data/datasource/local/dao/MoviesDao.kt
> +    suspend fun deleteMovie(movie: MoviesEntity)
delete movie-ს მთლიან ობიექტს რომ აწვდი შეიძლება მაგან რაღაცეებში შეგიშალოს ხელი მომავალში. წაშლის ფუნქცია მგონი ჯობია რო @Query-ში დაწერო ხელით და მხოლოდ movie id გადააწოდო იმიტორო იდეაში წაშლისთვის მეტი არც არაფერი გჭირდება და მთლიან ობიექტსაც ტყუილად გადააწვდი

2022-03-17 10:49 UTC, shioandghuladze commented on app/src/main/java/com/example/movieapp/data/datasource/local/entity/MoviesEntity.kt
> +    @PrimaryKey(autoGenerate = true) val id: Long? = null,
autoGenerate false გახადე და აიდად თვითონ API-დან წამოსული ფილმის აიდი გაატანე ხოლმე ძალიან დაგეხმარება ეგ რომ ერთმანეთთან დააკავშირო ბაზის ენთითიები და Api-დან წამოსული ობიექტები

2022-03-17 11:16 UTC, Gio481 commented on app/src/main/java/com/example/movieapp/data/datasource/local/dao/MoviesDao.kt
> +    suspend fun deleteMovie(movie: MoviesEntity)
done

2022-03-17 11:16 UTC, Gio481 commented on app/src/main/java/com/example/movieapp/data/datasource/local/entity/MoviesEntity.kt
> +    @PrimaryKey(autoGenerate = true) val id: Long? = null,
done

2022-03-17 11:18 UTC, shioandghuladze commented on app/src/main/java/com/example/movieapp/data/datasource/local/entity/MoviesEntity.kt
> +    @PrimaryKey(autoGenerate = false) val id: Long? = null,
დამავიწყდა მეთქვა :D რომ მოაშორე აუტოჯენერეითი ეხლა რომ არ გამოგრჩეს აიდის შეყვანა და არ დაიქრაშოს val id: Long? = null ის მაგივრად val id: Long დაწერე რომ თუ არ შეიყვან აიდის გაგიწითლოს

2022-03-17 11:43 UTC, Gio481 commented on app/src/main/java/com/example/movieapp/data/datasource/local/entity/MoviesEntity.kt
> +    @PrimaryKey(autoGenerate = false) val id: Long? = null,
done

2022-03-17 13:02 UTC, GiorgiMamagulashvili1 requested changes

2022-03-17 13:02 UTC, GiorgiMamagulashvili1 commented on app/src/main/java/com/example/movieapp/util/Constants.kt
> +    const val DATABASE_VERSION = 1
ამ ცვლადების კონსტანტები არაა საჭირო

2022-03-17 14:30 UTC, Gio481 commented on app/src/main/java/com/example/movieapp/util/Constants.kt
> +    const val DATABASE_VERSION = 1
არც სტრინგებში არც არაფერში ?

2022-03-17 14:32 UTC, GiorgiMamagulashvili1 commented on app/src/main/java/com/example/movieapp/util/Constants.kt
> +    const val DATABASE_VERSION = 1
არა არუნდა დეითაბეისის პარამეტრებს, მარტო ერთხელ შეიქმნება ეს პარამეტრები მაინც

2022-03-17 14:44 UTC, Gio481 commented on app/src/main/java/com/example/movieapp/util/Constants.kt
> +    const val DATABASE_VERSION = 1
Done

2022-03-18 08:12 UTC, GiorgiMamagulashvili1 approved these changes

2022-03-18 08:12 UTC, merged