[ARC-2047] Feature/fetch data from datasource/arc 2047
Gio481/MovieApp pull request #4
Opened 2022-03-21 11:20 UTC by Gio481

https://spaceneobank.atlassian.net/browse/ARC-2047

2022-03-21 11:26 UTC, GiorgiMamagulashvili1 requested changes

2022-03-21 11:26 UTC, GiorgiMamagulashvili1 commented on app/src/main/java/com/example/movieapp/data/repository/movies/MoviesRepositoryImpl.kt
> +        }
რაიმე გლობალური ფუნქცია გააკეთე try catch ის შემცვლელი

2022-03-21 11:30 UTC, AnaRusadze approved these changes

2022-03-22 06:08 UTC, GiorgiMamagulashvili1 approved these changes

2022-03-22 06:08 UTC, merged