[ARC-2049] Feature/implement adapter/arc 2049
Gio481/MovieApp pull request #6
Opened 2022-03-23 05:59 UTC by Gio481

https://spaceneobank.atlassian.net/browse/ARC-2049

2022-03-23 06:04 UTC, GiorgiMamagulashvili1 approved these changes
ფეიჯინგის ბიბლიოთეკის გარეშე გაკეთება არ გიცდია?

2022-03-23 08:04 UTC, Gio481 commented
> ფეიჯინგის ბიბლიოთეკის გარეშე გაკეთება არ გიცდია?

არა, პიდაპირ ამით ვცადე

2022-03-23 11:00 UTC, AnaRusadze requested changes

2022-03-23 11:00 UTC, AnaRusadze commented on app/src/main/java/com/example/movieapp/domain/model/FavouriteMoviesDomain.kt
> +    }
1. რეიტინგის სტრინგად გადაყვანა დატა კლასში არამგონია კარგი ვარიანტი იყოს, იმიტომ რომ მასზე შეიძლება სხვა ოპერაციების დამატება იყოს საჭირო. მაგალითად: ახლა მხოლოდ ვიზუალურად გამოჩენა გჭირდება, თუმცა რომ მოგთხოვონ, შეკრების ოპერაცია ან საშუალოს გამოთვლა (რამე მათემატიკური) სტრინგზე ვერ განახორციელებ. ამიტომ მნიშვნელოვანია რომ მისი საწყისი ტაიპი ის იყოს, რაც სერვერიდან მოდის, ხოლო სტრინგი სადაც დაგჭირდება, იქ გადაიყვანე

2. ზოგადად დატა კლასში ფუნქცია ამისთვის ზედმეტი იქნებოდა, ეგეთ შემთხვევაში get-ით შეგიძლია მიაღწიო მიზანს get()= rating.tosString(). ფუნქციას თუ დაწერ, ზმნის სახელი დაარქვი, getRating ან მსგავსი, თუმცა როგორც ვთქვი, ამ შემთხვევაში საერთოდ არ დაგჭირდება. შეგიძლია გამოიყენო სხვა პარამეტრებისთვის, მაგალითად: 
val posterUrl
        get()= "https://image.tmdb.org/t/p/w185$poster"

2022-03-23 11:00 UTC, AnaRusadze commented on app/src/main/res/values/dimens.xml
> +    <dimen name="dimen_1_dp">1dp</dimen>
ზრდის მიხედვით დაალაგე, უფრო მარტივი იქნება

2022-03-23 19:15 UTC, Gio481 commented on app/src/main/java/com/example/movieapp/domain/model/FavouriteMoviesDomain.kt
> +    }
done

2022-03-23 19:15 UTC, Gio481 commented on app/src/main/res/values/dimens.xml
> +    <dimen name="dimen_1_dp">1dp</dimen>
done

2022-03-24 07:34 UTC, shioandghuladze approved these changes

2022-03-24 18:04 UTC, merged